- Hi, my name is Andre
- I’m interested in learning how to code
- I’m currently majoring in CIS (freshman)
- I’m looking to collaborate on any type of project that can help me learn more 
- Any inquiries or collaborations to andrerequeyaipen16@gmail.com
- Pronouns: He/Him
